export const CATALOGO_PERMISOS = [
  { codigo: "dashboard.ver", modulo: "General", nombre: "Dashboard" },
  { codigo: "inventario.compania", modulo: "Inventario", nombre: "Inventario compañía" },
  { codigo: "inventario.bodegas", modulo: "Inventario", nombre: "Inventario bodegas" },
  { codigo: "items.ver", modulo: "Inventario", nombre: "Ítems" },
  { codigo: "bodegas.ver", modulo: "Inventario", nombre: "Bodegas" },
  { codigo: "inventario.gestionar", modulo: "Inventario físico", nombre: "Inventario" },
  { codigo: "inventario.reportes", modulo: "Inventario físico", nombre: "Reporte de inventarios físicos" },
  { codigo: "despacho.pedidos", modulo: "Despacho", nombre: "Pedidos" },
  { codigo: "despacho.reaprovisionamiento", modulo: "Despacho", nombre: "Reaprovisionamiento CEDIS" },
  { codigo: "despacho.cargues", modulo: "Despacho", nombre: "Cargues" },
  { codigo: "despacho.estado-cargues", modulo: "Despacho", nombre: "Estado de cargues" },
  { codigo: "despacho.asignacion-bodega", modulo: "Configuración", nombre: "Asignación de bodega" },
  { codigo: "despacho.muelles", modulo: "Configuración", nombre: "Muelles" },
  { codigo: "despacho.hojas-ruta", modulo: "Despacho", nombre: "Hojas de ruta" },
  { codigo: "despacho.ordenes-compra", modulo: "Despacho", nombre: "Órdenes de compra" },
  { codigo: "despacho.motivos", modulo: "Configuración", nombre: "Motivos de omisión" },
  { codigo: "despacho.firmantes", modulo: "Configuración", nombre: "Firmantes" },
  { codigo: "despacho.taras", modulo: "Configuración", nombre: "Taras o empaques" },
  { codigo: "despacho.aviso", modulo: "Despacho", nombre: "Aviso de despacho" },
  { codigo: "despacho.compromisos", modulo: "Despacho", nombre: "Enviar compromisos" },
  { codigo: "despacho.piso", modulo: "Despacho", nombre: "Piso despacho" },
  { codigo: "despacho.conductor", modulo: "Despacho", nombre: "Portal conductor" },
  { codigo: "despacho.liquidacion", modulo: "Despacho", nombre: "Cierre y liquidación" },
  { codigo: "seguridad.permisos", modulo: "Configuración", nombre: "Permisos" },
  { codigo: "seguridad.perfiles", modulo: "Configuración", nombre: "Perfiles" },
  { codigo: "seguridad.usuarios", modulo: "Configuración", nombre: "Usuarios" },
  { codigo: "vehiculos.ver", modulo: "Configuración", nombre: "Vehículos" },
  { codigo: "mesas.ver", modulo: "Configuración", nombre: "Mesas" },
  { codigo: "colaboradores.ver", modulo: "Configuración", nombre: "Colaboradores" },
  { codigo: "basculas.ver", modulo: "Configuración", nombre: "Básculas" },
];

export const todosLosCodigos = () => CATALOGO_PERMISOS.map((item) => item.codigo);
